### ISSUE TITLE
heroku mongDB がクレジットカード登録しないと使えない

### ISSUE THREAD

**Issue by nazoking** [team-lab/skillup-nodejs#25]
注意書きが必要

できれば別の方法を見付ける
- Microsoft Azure の学生無料プラン https://www.dreamspark.com/Product/Product.aspx?productid=99
- ずっと無料で使えるPaaS型クラウドのまとめ。2011年版 http://www.publickey1.jp/blog/11/paas2011.html

**Comment by nazoking** [comment]
調べる
 * https://mongolab.com/home ←単体で使えないか？
 * https://lite.nitrous.io/ ← 無料プラン終わり？　使えるなら mysql php nodejs 使えるので、ローカル環境準備できない人でも利用できるようになるかも

**Comment by morishitashigeya** [comment]
https://mongolab.com/home ←単体でもHerokuから利用可能でした

**Comment by nazoking** [comment]
#29
