### ISSUE TITLE
気になったこと

### ISSUE THREAD

**Issue by kyohei8** [team-lab/skillup-nodejs#8]
修正はしてないですが、気になったことを。

 * nodeパッケージのバージョン  
expressやconnect、socket.ioのメジャーバージョンが少し前に上がっているので、
書いてあるコードが動かない場合がありそう。
→バージョンの指定があったほうがいいかも。（その都度メンテするでもいいけど）

* jade関連の部分はなくてもいいかも  
ただでさえ覚えてもらうことが多いので、ここは普通にejsで書くだけでいいと思いました。(jadeは参考程度くらいでも)

**Comment by nazoking** [comment]
たしかにjade必要なさそうだけど簡単にとれない感じですね・・・

**Comment by dolpen** [comment]
expressから最初の雛形作るときに、viewsにjade入ってしまいますし。。

**Comment by kyohei8** [comment]
オプションでejsに変える
```
$ express myapp --ejs
```
はダメなんですかね？
http://expressjs.com/starter/generator.html

**Comment by nazoking** [comment]
@kyohei8 @dolpen ひな型はそのオプションでいいと思います！

ドキュメントやサンプルでjadeで書いてあるところがいくつかあるので、それの文章量がけっこうあるかなーと思いました
